version: "2"

services:
  jira:
    image: vulhub/jira:7.13.4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - smtpd
  
  smtpd:
    image: vulhub/smtpd:python3.6
    build:
      context: .
      dockerfile: smtpd.Dockerfile